name: Deploy Website to Hostalia

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy to Hostalia
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: ⚙️ Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: 📦 Install dependencies
      run: npm ci

    - name: 🏗️ Build Project
      run: npm run build

    - name: 📂 Sync files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: ./

    - name: 🔔 Trigger Hostalia Git Pull & Deploy
      run: |
        curl -k -X POST "https://plw205.dns-servicio.com:8443/modules/git/public/web-hook.php?uuid=89d01af6-1ecd-d52a-8e02-9e44817ebb36"
